import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {mkdtempSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {openStore,passwordHash,now} from '../store.mjs';
import {createApp} from '../server.mjs';
import sharp from 'sharp';
const base='http://127.0.0.1:3100',secret='sk_test_fixture';
const fixture=()=>({name:'Test customer',email:'customer@example.test',phone:'08012345678',method:'pickup',items:[{variant:'v',quantity:1}],idempotency:randomUUID()});
async function app(config={}){const s=openStore(':memory:');s.saveProduct({id:'p',name:'Test item',description:'Fixture only',category:'Bags',photo:'',visible:true,variants:[{id:'v',colour:'Test',size:'Test',price:120000,cost:50000,stock:3}]});const a=createApp({store:s,config:{baseUrl:base,payment:'paystack',email:'development',production:false,secret,...config},env:{DATABASE_PATH:join(mkdtempSync(join(tmpdir(),'bagz-http-')),'store.sqlite')}});await new Promise(r=>a.server.listen(0,'127.0.0.1',r));return {...a,url:'http://127.0.0.1:'+a.server.address().port,close:async()=>{await new Promise(r=>a.server.close(r));s.db.close();}};}
test('HTTP signed duplicate webhooks reverify remotely but settle only once',async()=>{const a=await app(),o=a.store.createOrder(fixture()),fetchReal=globalThis.fetch;let verifications=0;globalThis.fetch=async(url,options)=>{if(String(url).startsWith('https://api.paystack.co/transaction/verify/')){verifications++;return new Response(JSON.stringify({status:true,data:{id:1234,domain:'test',status:'success',reference:o.reference,amount:o.total,currency:'NGN',metadata:{order_id:o.id},customer:{email:o.email}}}),{status:200,headers:{'Content-Type':'application/json'}});}return fetchReal(url,options);};try{const raw=JSON.stringify({event:'charge.success',data:{reference:o.reference}}),headers={'x-paystack-signature':createHmac('sha512',secret).update(raw).digest('hex'),'Content-Type':'application/json'};for(let i=0;i<2;i++)assert.equal((await fetchReal(a.url+'/api/webhook/paystack',{method:'POST',headers,body:raw})).status,200);assert.equal(verifications,2);assert.equal(a.store.get('SELECT stock FROM variants').stock,2);assert.equal(a.store.all('SELECT * FROM notifications').length,3);assert.equal((await fetchReal(a.url+'/api/webhook/paystack',{method:'POST',headers,body:raw+' '})).status,401);}finally{globalThis.fetch=fetchReal;await a.close();}});
test('provider timeout leaves the order unpaid for reconciliation',async()=>{const a=await app(),o=a.store.createOrder(fixture()),original=globalThis.fetch;globalThis.fetch=async()=>{throw Error('Test timeout');};try{await assert.rejects(a.svc.verify(o));assert.equal(a.store.get('SELECT payment FROM orders').payment,'pending');assert.match(a.store.get('SELECT payment_check_error FROM orders').payment_check_error,/timeout/);assert.equal(a.store.all('SELECT * FROM notifications').length,0);}finally{globalThis.fetch=original;await a.close();}});
test('expired checkout cannot start a new payment',async()=>{const a=await app({payment:'development'}),o=a.store.createOrder(fixture());a.store.run('UPDATE orders SET expires=?',now()-1);try{const r=await fetch(a.url+'/api/order/'+o.token+'/pay',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,409);}finally{await a.close();}});
test('production API cannot invoke the development success adapter',async()=>{const a=await app({production:true}),o=a.store.createOrder(fixture());try{const r=await fetch(a.url+'/api/order/'+o.token+'/simulate',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:'{"status":"success"}'});assert.equal(r.status,404);assert.equal(a.store.get('SELECT payment FROM orders').payment,'pending');}finally{await a.close();}});
test('owner upload rejects executable/SVG content and rewrites valid photos to WebP',async()=>{const a=await app({payment:'development'});a.store.run('INSERT INTO owner VALUES(1,?,?)','owner@example.test',passwordHash('test-password-123456'));try{const r=await fetch(a.url+'/api/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({email:'owner@example.test',password:'test-password-123456'})});const cookie=r.headers.get('set-cookie').split(';')[0],{csrf}=await r.json(),headers={Origin:base,Cookie:cookie,'X-CSRF-Token':csrf};assert.equal((await fetch(a.url+'/api/admin/upload',{method:'POST',headers,body:'<svg onload="alert(1)"></svg>'})).status,400);const png=await sharp({create:{width:12,height:12,channels:3,background:'#fff'}}).png().toBuffer();const uploaded=await fetch(a.url+'/api/admin/upload',{method:'POST',headers,body:png});assert.equal(uploaded.status,200);const {url}=await uploaded.json();assert.match(url,/^\/uploads\/[a-f0-9-]+\.webp$/);const read=await fetch(a.url+url);assert.equal(read.status,200);assert.equal((await sharp(Buffer.from(await read.arrayBuffer())).metadata()).format,'webp');}finally{await a.close();}});
