import http from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash, randomUUID } from 'node:crypto';
import { openStore, Problem, now, token, string, integer, email, passwordMatches, passwordHash } from './store.mjs';
import { commerce } from './commerce.mjs';
import { configuration, services, validSignature } from './services.mjs';
const root=dirname(fileURLToPath(import.meta.url));
export function createApp({store=openStore(process.env.DATABASE_PATH),config=configuration(),env=process.env}={}) {
  const extra=commerce(store),svc=services(store,config,env),uploads=resolve(dirname(resolve(env.DATABASE_PATH||'./data/store.sqlite')),'uploads');
  const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
  function rate(key,max=30) {const row=store.get('SELECT * FROM rate_limits WHERE key=?',key);if(!row||row.expires<now()){store.run('INSERT OR REPLACE INTO rate_limits VALUES(?,?,?)',key,1,now()+60000);return;}if(row.count>=max)throw new Problem('Too many requests; try again in a minute',429);store.run('UPDATE rate_limits SET count=count+1 WHERE key=?',key);}
  async function body(req,max=100000) {const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>max)throw new Problem('Upload/request too large',413);chunks.push(c);}return Buffer.concat(chunks);}
  function session(req) {const sid=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('session='))?.slice(8);const s=store.get('SELECT * FROM sessions WHERE id=? AND expires>?',sid||'',now());if(!s)throw new Problem('Owner sign-in required',401);if(req.method!=='GET'&&req.headers['x-csrf-token']!==s.csrf)throw new Problem('Invalid security token',403);return s;}
  const server=http.createServer(async(req,res)=>{
    res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'; object-src 'none'");if(config.production)res.setHeader('Strict-Transport-Security','max-age=31536000');
    try {
      const url=new URL(req.url,'http://localhost'),path=url.pathname;
      const mutation=!['GET','HEAD'].includes(req.method);
      if(mutation&&path!=='/api/webhook/paystack'&&req.headers.origin!==config.baseUrl)throw new Problem('Request origin not allowed',403);
      if(path==='/api/webhook/paystack'&&req.method==='POST') {const raw=await body(req);if(config.payment!=='paystack'||!validSignature(raw,req.headers['x-paystack-signature'],config.secret))throw new Problem('Invalid webhook signature',401);const event=JSON.parse(raw);if(event.event==='charge.success'){const o=store.get('SELECT * FROM orders WHERE reference=?',String(event.data?.reference));if(!o)throw new Problem('Unknown reference',404);await svc.verify(o);}json(res,{received:true});return;}
      if(path.startsWith('/api/')) {
        const admin=path.startsWith('/api/admin/')?session(req):null;
        if(mutation)rate((req.socket.remoteAddress||'unknown')+':'+(path.includes('login')?'login':admin?'admin':'public'),path.includes('login')?5:90);
        let data={}; if(mutation&&!path.endsWith('/upload')){const raw=await body(req);try{data=raw.length?JSON.parse(raw):{};}catch{throw new Problem('Invalid JSON');}}
        const localSetup=!config.production&&['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress)&&['localhost','127.0.0.1','[::1]'].includes(new URL(config.baseUrl).hostname);
        const setupEnabled=!store.get('SELECT id FROM owner WHERE id=1')&&(localSetup||env.OWNER_SETUP_CODE?.length>=32);
        if(path==='/api/setup'&&req.method==='GET'){json(res,{enabled:!!setupEnabled,codeRequired:!localSetup});return;}
        if(path==='/api/setup'&&req.method==='POST'){
          rate((req.socket.remoteAddress||'unknown')+':setup',5);
          if(!setupEnabled)throw new Problem('Owner setup is unavailable',403);
          if(!localSetup&&createHash('sha256').update(String(data.code||'')).digest('hex')!==createHash('sha256').update(env.OWNER_SETUP_CODE).digest('hex'))throw new Problem('Incorrect setup code',403);
          const address=email(data.email),password=string(data.password,'password',300);if(password.length<14)throw new Problem('Use at least 14 characters');
          store.tx(()=>{if(store.get('SELECT id FROM owner WHERE id=1'))throw new Problem('Owner already exists',409);store.run('INSERT INTO owner VALUES(1,?,?)',address,passwordHash(password));const settings=store.settings();store.saveSettings({...settings,ownerEmail:address});store.audit('Owner account created');});json(res,{ok:true});return;
        }
        if(path==='/api/shop'&&req.method==='GET'){const s=store.settings();json(res,{settings:{brand:s.brand,logo:s.logo,tagline:s.tagline,bagDisplay:s.bagDisplay,shoeDisplay:s.shoeDisplay,whatsapp:s.whatsapp,pickupInstructions:s.pickupInstructions,pickupTime:s.pickupTime,deliveryAreas:s.deliveryAreas},content:extra.content(),products:extra.enrichProducts(store.catalogue().filter(p=>!config.production||!p.sample)),mode:config.payment==='development'?'development':config.payment==='disabled'?'disabled':'Paystack test'});return;}
        if(path==='/api/login'&&req.method==='POST'){const owner=store.get('SELECT * FROM owner WHERE id=1');const pass=string(data.password,'password',300);const hash=owner?.password||passwordHash('unused-dummy-password');const matches=passwordMatches(pass,hash);if(!owner||String(data.email).toLowerCase()!==owner.email||!matches)throw new Problem('Incorrect email or password',401);const id=token(),csrf=token();store.run('INSERT INTO sessions VALUES(?,?,?)',id,csrf,now()+12*3600000);res.setHeader('Set-Cookie',`session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${config.production?'; Secure':''}`);json(res,{csrf});return;}
        if(path==='/api/checkout'&&req.method==='POST'){if(config.payment==='disabled')throw new Problem('Checkout is not open yet. Please contact the shop for assistance.',503);const hash=createHash('sha256').update(JSON.stringify(data)).digest('hex');if(config.production&&data.items?.some(i=>store.get('SELECT p.sample FROM products p JOIN variants v ON v.product_id=p.id WHERE v.id=?',i.variant)?.sample))throw new Problem('Sample items cannot be purchased in production');const o=store.createOrder(data,{hash});json(res,{statusUrl:'/order/'+o.token,order:store.publicOrder(o)});return;}
        const orderMatch=path.match(/^\/api\/order\/([a-f0-9]{64})(?:\/(pay|verify|simulate))?$/);
        if(orderMatch){let o=store.get('SELECT * FROM orders WHERE token=?',orderMatch[1]);if(!o)throw new Problem('Order not found',404);const action=orderMatch[2];if(!action&&req.method==='GET'){json(res,{...store.publicOrder(o),timeline:extra.timeline(o.id)});return;}if(req.method==='POST'&&action==='pay'){json(res,{checkout:await svc.initialize(o)});return;}if(req.method==='POST'&&action==='verify'){o=await svc.verify(o);json(res,store.publicOrder(o));return;}if(req.method==='POST'&&action==='simulate'){if(config.production||config.payment!=='development')throw new Problem('Development adapter disabled',404);if(!['success','failed','abandoned'].includes(data.status))throw new Problem('Invalid development result');o=store.finalize(o.reference,{id:'dev_'+o.id,domain:'test',reference:o.reference,amount:o.total,currency:'NGN',metadata:{order_id:o.id},customer:{email:o.email},status:data.status},config.baseUrl);json(res,store.publicOrder(o));return;}}
        if(admin){
          if(path==='/api/admin/insights'&&req.method==='GET'){json(res,extra.overview(config,env));return;}
          if(path==='/api/admin/customers'&&req.method==='GET'){json(res,extra.customers());return;}
          if(path==='/api/admin/analytics'&&req.method==='GET'){json(res,extra.analytics(url.searchParams.get('from')||'',url.searchParams.get('to')||''));return;}
          if(path==='/api/admin/export'&&req.method==='GET'){const kind=url.searchParams.get('type')||'orders';const csv=extra.exportCsv(kind,url.searchParams.get('from')||'',url.searchParams.get('to')||'');res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="bagz-'+kind+'.csv"'});res.end(csv);return;}
          if(path==='/api/admin/order-detail'&&req.method==='GET'){json(res,extra.orderDetails(url.searchParams.get('id')||''));return;}
          if(path==='/api/admin/note'&&req.method==='POST'){extra.note(data);json(res,{ok:true});return;}
          if(path==='/api/admin/stock'&&req.method==='POST'){json(res,extra.adjustStock(data));return;}
          if(path==='/api/admin/stock-history'&&req.method==='GET'){json(res,store.all('SELECT m.*,p.name,v.colour,v.size FROM stock_movements m JOIN variants v ON v.id=m.variant_id JOIN products p ON p.id=v.product_id ORDER BY m.created DESC LIMIT 100'));return;}
          if(path==='/api/admin/content'&&req.method==='POST'){json(res,extra.saveContent(data));return;}
          if(path==='/api/admin/content'&&req.method==='GET'){json(res,extra.content());return;}
          if(path==='/api/admin/read-all'&&req.method==='POST'){store.run("UPDATE notifications SET read=1 WHERE channel='dashboard'");json(res,{ok:true});return;}
          if(path==='/api/admin/resolve-hold'&&req.method==='POST'){extra.resolveHold(string(data.id,'order',80),data.confirmed,config.baseUrl);json(res,{ok:true});return;}
          if(path==='/api/admin/security'&&req.method==='POST'){const owner=store.get('SELECT * FROM owner WHERE id=1');if(!owner||!passwordMatches(string(data.currentPassword,'current password',300),owner.password))throw new Problem('Current password is incorrect',403);const next=string(data.newPassword,'new password',300);if(next.length<14)throw new Problem('Use at least 14 characters');store.tx(()=>{store.run('UPDATE owner SET password=? WHERE id=1',passwordHash(next));store.run('DELETE FROM sessions');store.audit('Owner password changed; all sessions revoked');});res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');json(res,{ok:true});return;}

          if(path==='/api/admin/me'&&req.method==='GET'){json(res,{csrf:admin.csrf,pushKey:env.VAPID_PUBLIC_KEY||'',mode:config.payment});return;}
          if(path==='/api/admin/logout'&&req.method==='POST'){store.run('DELETE FROM sessions WHERE id=?',admin.id);res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');json(res,{ok:true});return;}
          if(path==='/api/admin/overview'&&req.method==='GET'){json(res,{report:store.report(),orders:store.all('SELECT * FROM orders ORDER BY created DESC').map(o=>({...o,items:store.all('SELECT * FROM items WHERE order_id=?',o.id)})),products:extra.enrichProducts(store.catalogue(true)),notifications:store.all('SELECT * FROM notifications ORDER BY created DESC LIMIT 200'),settings:store.settings(),expenses:store.all('SELECT * FROM expenses ORDER BY created DESC LIMIT 100'),refunds:store.all('SELECT * FROM refunds ORDER BY created DESC LIMIT 100')});return;}
          if(path==='/api/admin/delete-product'&&req.method==='POST'){store.deleteProduct(string(data.id,'product',80));json(res,{ok:true});return;}
          if(path==='/api/admin/product'&&req.method==='POST'){const id=store.tx(()=>{const id=store.saveProduct(data);extra.saveDetails(id,data);return id;});json(res,{id});return;}
          if(path==='/api/admin/settings'&&req.method==='POST'){json(res,store.saveSettings(data));return;}
          if(path==='/api/admin/custom'&&req.method==='POST'){const o=store.createOrder(data,{custom:true,hash:createHash('sha256').update(JSON.stringify(data)).digest('hex')});json(res,{url:config.baseUrl+'/order/'+o.token,number:o.number,expires:o.expires});return;}
          if(path==='/api/admin/expense'&&req.method==='POST'){store.run('INSERT INTO expenses VALUES(?,?,?,?)',randomUUID(),string(data.description,'description',300),integer(data.amount,'amount',1,1000000000),now());json(res,{ok:true});return;}
          if(path==='/api/admin/order'&&req.method==='POST'){const id=string(data.id,'order',80);if(data.action==='fulfil')store.fulfil(id,data.state,config.baseUrl);else if(data.action==='cancel')store.cancel(id,config.baseUrl);else if(data.action==='restock'){if(data.confirmPhysicalReturn!==true)throw new Problem('Confirm items are physically available again');store.restock(id);}else if(data.action==='verify'){const o=store.get('SELECT * FROM orders WHERE id=?',id);if(!o)throw new Problem('Order not found',404);await svc.verify(o);}else if(data.action==='refund'){if(config.payment!=='paystack')throw new Problem('Refund confirmation requires Paystack test credentials');const rid=string(data.refundId,'refund ID',80);if(!/^[a-zA-Z0-9_-]+$/.test(rid))throw new Problem('Invalid refund ID');store.refund(id,await svc.paystack('/refund/'+rid),config.baseUrl);}else throw new Problem('Unknown action');json(res,{ok:true});return;}
          if(path==='/api/admin/notification'&&req.method==='POST'){const id=string(data.id,'notification',80);if(data.action==='read')store.run('UPDATE notifications SET read=1 WHERE id=?',id);else if(data.action==='retry')store.run("UPDATE notifications SET status='pending' WHERE id=? AND status IN ('failed','development')",id);else throw new Problem('Unknown action');json(res,{ok:true});return;}
          if(path==='/api/admin/push'&&req.method==='POST'){const sub=data.subscription;if(!sub||typeof sub.endpoint!=='string'||sub.endpoint.length>2000||!sub.keys?.p256dh||!sub.keys?.auth)throw new Problem('Invalid push subscription');const u=new URL(sub.endpoint);if(u.protocol!=='https:'||!['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))throw new Problem('Unsupported push service');store.run('INSERT OR REPLACE INTO subscriptions VALUES(?,?)',sub.endpoint,JSON.stringify(sub));json(res,{ok:true});return;}
          if(path==='/api/admin/upload'&&req.method==='POST'){const raw=await body(req,5*1024*1024);const {default:sharp}=await import('sharp');let image;try{const instance=sharp(raw,{limitInputPixels:24000000,failOn:'warning'});const meta=await instance.metadata();if(!['jpeg','png','webp'].includes(meta.format)||meta.pages>1)throw Error();image=await instance.rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer();}catch{throw new Problem('Upload a valid JPEG, PNG or WebP image up to 5 MB and 24 megapixels');}await mkdir(uploads,{recursive:true});const name=randomUUID()+'.webp';await writeFile(resolve(uploads,name),image,{flag:'wx'});json(res,{url:'/uploads/'+name});return;}
        }
        throw new Problem('API route not found',404);
      }
      if(!['GET','HEAD'].includes(req.method))throw new Problem('Method not allowed',405);
      let file;if(/^\/uploads\/[a-f0-9-]+\.webp$/.test(path))file=resolve(uploads,path.slice(9));else if(['/oreva-logo.jpg','/display-loafers.jpg','/display-flats.jpg','/display-bag-pink.jpg','/display-bag-rose.jpg','/display-bag-burgundy.jpg','/campaign.css','/campaign-bag.png','/enhancements.js','/enhancements.css','/editorial.css','/editorial-hero.png','/oreva-logo.jpg','/app.js','/style.css','/sw.js','/manifest.webmanifest','/sample-bag.svg','/sample-shoe.svg'].includes(path))file=resolve(root,'public',path.slice(1));else if(path==='/health'){json(res,{ok:true});return;}else file=resolve(root,'public/index.html');
      let content;try{content=await readFile(file);}catch{throw new Problem('File not found',404);}const type={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.webmanifest':'application/manifest+json'}[extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type+'; charset=utf-8'});res.end(req.method==='HEAD'?undefined:content);
    }catch(e){if(!res.headersSent)json(res,{error:e instanceof Problem?e.message:'Request could not be completed'},e.status||500);else res.end();if(!(e instanceof Problem))console.error('Server error:',e.message);}
  });
  let reconciling=false;
  const timer=setInterval(async()=>{await svc.processNotifications();if(config.payment==='paystack'&&!reconciling){reconciling=true;try{for(const o of store.all("SELECT * FROM orders WHERE payment<>'paid' AND created>? ORDER BY payment_checked ASC LIMIT 20",now()-7*86400000)){try{await svc.verify(o);}catch{/* visible for owner retry; no false success */}}}finally{reconciling=false;}}store.run('DELETE FROM sessions WHERE expires<?',now());store.run('DELETE FROM rate_limits WHERE expires<?',now());},30000);timer.unref();server.on('close',()=>clearInterval(timer));return {server,store,svc};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const {server}=createApp();server.listen(Number(process.env.PORT||3100),process.env.HOST||'127.0.0.1',()=>console.log(`Store ready at ${process.env.BASE_URL||'http://127.0.0.1:3100'} (test payments only)`));}
