import { DatabaseSync } from 'node:sqlite';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

export class Problem extends Error { constructor(message, status=400) { super(message); this.status=status; } }
export const token = () => randomBytes(32).toString('hex');
export const now = () => Date.now();
export const money = n => new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(n/100);
export function string(v, name, max=500, optional=false) { if (typeof v !== 'string' || (!optional && !v.trim()) || v.length>max) throw new Problem(`Invalid ${name}`); return v.trim(); }
export function integer(v,name,min=0,max=1000000000) { if (!Number.isSafeInteger(v)||v<min||v>max) throw new Problem(`Invalid ${name}`); return v; }
export function email(v) { const s=string(v,'email',254).toLowerCase(); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)) throw new Problem('Enter a valid email'); return s; }
export function phone(v) { let s=string(v,'phone',30).replace(/[\s()-]/g,''); if(/^0[789]\d{9}$/.test(s)) s='+234'+s.slice(1); if(!/^\+234[789]\d{9}$/.test(s)) throw new Problem('Enter a Nigerian phone number, e.g. 080… or +234…'); return s; }
export function passwordHash(password,salt=randomBytes(16).toString('hex')) { return salt+':'+scryptSync(password,salt,64).toString('hex'); }
export function passwordMatches(password,hash) { if(!hash) return false; const [salt,h]=hash.split(':'); return timingSafeEqual(Buffer.from(h,'hex'),scryptSync(password,salt,64)); }
const defaults={brand:'Orẽva',logo:'/oreva-logo.jpg',tagline:'Timeless elegance.',ownerEmail:'',whatsapp:'',pickupInstructions:'Pickup instructions will be shared by the owner.',pickupTime:'1–2 working days after payment',deliveryAreas:[],lowStock:3,emailEnabled:true,pushEnabled:false};

export function openStore(path='./data/store.sqlite') {
  if(path!==':memory:') mkdirSync(dirname(resolve(path)),{recursive:true});
  const db=new DatabaseSync(path);
  db.exec(`PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
    CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),json TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS owner(id INTEGER PRIMARY KEY CHECK(id=1),email TEXT NOT NULL,password TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,csrf TEXT NOT NULL,expires INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,photo TEXT NOT NULL DEFAULT '',visible INTEGER NOT NULL,sample INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE IF NOT EXISTS variants(id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),colour TEXT NOT NULL,size TEXT NOT NULL,price INTEGER NOT NULL CHECK(price>=0),cost INTEGER NOT NULL CHECK(cost>=0),stock INTEGER NOT NULL CHECK(stock>=0));
    CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,number TEXT UNIQUE NOT NULL,token TEXT UNIQUE NOT NULL,reference TEXT UNIQUE NOT NULL,idempotency TEXT UNIQUE NOT NULL,request_hash TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,method TEXT NOT NULL,delivery INTEGER NOT NULL,timeframe TEXT NOT NULL,instructions TEXT NOT NULL,total INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'NGN',payment TEXT NOT NULL DEFAULT 'pending',fulfilment TEXT NOT NULL DEFAULT 'Awaiting payment',reserved INTEGER NOT NULL DEFAULT 1,allocated INTEGER NOT NULL DEFAULT 0,exception TEXT NOT NULL DEFAULT '',expires INTEGER NOT NULL,created INTEGER NOT NULL,paid_at INTEGER,transaction_id TEXT UNIQUE,receipt TEXT UNIQUE,custom INTEGER NOT NULL DEFAULT 0,cancelled INTEGER NOT NULL DEFAULT 0,refunded INTEGER NOT NULL DEFAULT 0,restocked INTEGER NOT NULL DEFAULT 0,checkout_url TEXT,payment_checked INTEGER NOT NULL DEFAULT 0,payment_check_error TEXT NOT NULL DEFAULT '');
    CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),variant_id TEXT REFERENCES variants(id),name TEXT NOT NULL,colour TEXT NOT NULL,size TEXT NOT NULL,quantity INTEGER NOT NULL,price INTEGER NOT NULL,cost INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,dedupe TEXT UNIQUE NOT NULL,order_id TEXT REFERENCES orders(id),channel TEXT NOT NULL,recipient TEXT NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',created INTEGER NOT NULL,locked_until INTEGER NOT NULL DEFAULT 0,read INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE IF NOT EXISTS subscriptions(endpoint TEXT PRIMARY KEY,json TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS expenses(id TEXT PRIMARY KEY,description TEXT NOT NULL,amount INTEGER NOT NULL,created INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS refunds(id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),amount INTEGER NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,event TEXT NOT NULL,order_id TEXT,created INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS archived_products(id TEXT PRIMARY KEY REFERENCES products(id),created INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
    CREATE INDEX IF NOT EXISTS item_variant ON items(variant_id);
    CREATE INDEX IF NOT EXISTS order_pending ON orders(payment,expires);`);
  for(const [column,definition] of [['payment_checked','INTEGER NOT NULL DEFAULT 0'],['payment_check_error',"TEXT NOT NULL DEFAULT ''"]]) {if(!db.prepare('PRAGMA table_info(orders)').all().some(c=>c.name===column))db.exec(`ALTER TABLE orders ADD COLUMN ${column} ${definition}`);}
  db.prepare('INSERT OR IGNORE INTO settings VALUES(1,?)').run(JSON.stringify(defaults));
  const get=(sql,...p)=>db.prepare(sql).get(...p), all=(sql,...p)=>db.prepare(sql).all(...p), run=(sql,...p)=>db.prepare(sql).run(...p);
  let transactionDepth=0;
  const tx=fn=>{ const depth=transactionDepth, savepoint='nested_'+depth;db.exec(depth?'SAVEPOINT '+savepoint:'BEGIN IMMEDIATE');transactionDepth++;try{const result=fn();db.exec(depth?'RELEASE '+savepoint:'COMMIT');return result;}catch(error){db.exec(depth?'ROLLBACK TO '+savepoint:'ROLLBACK');if(depth)db.exec('RELEASE '+savepoint);throw error;}finally{transactionDepth--;}};
  const settings=()=>JSON.parse(get('SELECT json FROM settings WHERE id=1').json);
  function available(id,except='') { const v=get('SELECT stock FROM variants WHERE id=?',id); if(!v) throw new Problem('Variant not found'); return v.stock-Number(get(`SELECT COALESCE(SUM(i.quantity),0) AS q FROM items i JOIN orders o ON o.id=i.order_id WHERE i.variant_id=? AND o.id<>? AND o.reserved=1 AND o.expires>? AND o.payment='pending' AND o.cancelled=0`,id,except,now()).q); }
  function catalogue(admin=false) { return all(`SELECT * FROM products WHERE id NOT IN (SELECT id FROM archived_products) ${admin?'':'AND visible=1 AND sample=0'}`).map(p=>({...p,variants:all('SELECT * FROM variants WHERE product_id=?',p.id).map(v=>{const r={...v,available:available(v.id)}; if(!admin) delete r.cost;return r;})})); }
  const audit=(event,id=null)=>run('INSERT INTO audit(event,order_id,created) VALUES(?,?,?)',event,id,now());
  function enqueue(dedupe,order,channel,recipient,subject,body) { run('INSERT OR IGNORE INTO notifications(id,dedupe,order_id,channel,recipient,subject,body,created) VALUES(?,?,?,?,?,?,?,?)',randomUUID(),dedupe,order,channel,recipient,subject,body,now()); }
  function notify(o,kind,baseUrl) {
    const s=settings(), link=`${baseUrl}/order/${o.token}`;
    const body=`${s.brand}\nOrder ${o.number}\n${kind}\nPayment: ${o.payment}. Fulfilment: ${o.fulfilment}.\nTotal: ${money(o.total)}\n${o.receipt?'Receipt: '+o.receipt+'\n':''}${all('SELECT * FROM items WHERE order_id=?',o.id).map(i=>`${i.quantity} × ${i.name} (${i.colour}, ${i.size}) — ${money(i.quantity*i.price)}`).join('\n')}\nDelivery: ${money(o.delivery)}\nEstimated timeframe: ${o.timeframe}\n${o.instructions}\nSecure status and receipt: ${link}`;
    enqueue(`${o.id}:${kind}:dashboard`,o.id,'dashboard','owner',`${kind} · ${o.number}`,'Open the order in your dashboard.');
    if(s.emailEnabled) { enqueue(`${o.id}:${kind}:customer`,o.id,'email',o.email,`${s.brand}: ${kind} · ${o.number}`,body); if(kind==='Payment verified') enqueue(`${o.id}:${kind}:owner`,o.id,'email',s.ownerEmail,`Paid order · ${o.number}`,body); }
    if(s.pushEnabled) enqueue(`${o.id}:${kind}:push`,o.id,'push','owner','Store update','An order needs your attention. Open your dashboard.');
  }
  function createOrder(input,{custom=false,baseUrl='',hash=''}={}) { return tx(()=>{
    const idem=string(input.idempotency,'checkout key',100); const existing=get('SELECT * FROM orders WHERE idempotency=?',idem); if(existing) { if(existing.request_hash!==hash) throw new Problem('Checkout key already used for different details',409);return existing; }
    const s=settings(), customer={name:string(input.name,'name',120),email:email(input.email),phone:phone(input.phone)};
    const method=string(input.method,'fulfilment method',80); let delivery=0,timeframe=s.pickupTime,instructions=s.pickupInstructions,address='';
    if(method!=='pickup') { const area=s.deliveryAreas.find(a=>a.id===method); if(!area) throw new Problem('Choose an available delivery area'); delivery=area.fee;timeframe=area.timeframe;address=string(input.address,'delivery address',500);instructions='Delivery to '+address; }
    let lines=[];
    if(custom) { if(input.physicallyAvailable!==true) throw new Problem('Confirm that this custom item is physically available before taking payment'); lines=[{variant_id:null,name:string(input.description,'custom item description'),colour:string(input.colour,'colour',80),size:string(input.size,'size',80),quantity:integer(input.quantity,'quantity',1,100),price:integer(input.price,'price',100,100000000),cost:integer(input.cost,'supplier cost',0,100000000)}]; }
    else { if(!Array.isArray(input.items)||!input.items.length||input.items.length>30) throw new Problem('Choose 1–30 items'); const merged=new Map(); for(const i of input.items) { string(i.variant,'variant',80); merged.set(i.variant,(merged.get(i.variant)||0)+integer(i.quantity,'quantity',1,100)); }
      for(const [id,q] of merged) { const v=get('SELECT v.*,p.name,p.visible,p.sample FROM variants v JOIN products p ON p.id=v.product_id WHERE v.id=?',id); if(!v||!v.visible||(process.env.NODE_ENV==='production'&&v.sample)) throw new Problem('This item is unavailable'); if(available(id)<q) throw new Problem(`${v.name}: not enough stock`,409); lines.push({variant_id:id,name:v.name,colour:v.colour,size:v.size,quantity:q,price:v.price,cost:v.cost}); }
    }
    const total=lines.reduce((a,l)=>a+l.price*l.quantity,delivery); integer(total,'order total',100,1000000000);
    const id=randomUUID(),number='ACU-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+randomBytes(4).toString('hex').toUpperCase();
    run(`INSERT INTO orders(id,number,token,reference,idempotency,request_hash,name,email,phone,address,method,delivery,timeframe,instructions,total,expires,created,custom) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,number,token(),'acu_'+randomBytes(20).toString('hex'),idem,hash,customer.name,customer.email,customer.phone,address,method,delivery,timeframe,instructions,total,now()+30*60*1000,now(),custom?1:0);
    for(const l of lines) run('INSERT INTO items(order_id,variant_id,name,colour,size,quantity,price,cost) VALUES(?,?,?,?,?,?,?,?)',id,l.variant_id,l.name,l.colour,l.size,l.quantity,l.price,l.cost);
    audit('Order created; 30-minute reservation',id); return get('SELECT * FROM orders WHERE id=?',id);
  }); }
  function finalize(reference,data,baseUrl) { return tx(()=>{
    const o=get('SELECT * FROM orders WHERE reference=?',reference); if(!o) throw new Problem('Unknown payment reference',404);
    if(data.reference!==o.reference||data.amount!==o.total||data.currency!=='NGN'||String(data.metadata?.order_id)!==o.id||String(data.customer?.email).toLowerCase()!==o.email||!data.id||data.domain!=='test') throw new Problem('Payment verification details do not match the order',409);
    if(o.payment==='paid') { if(o.transaction_id!==String(data.id)) throw new Problem('Transaction mismatch',409); return o; }
    if(data.status!=='success') { if(['failed','abandoned'].includes(data.status)) run("UPDATE orders SET payment=?,reserved=0 WHERE id=?",data.status,o.id); audit('Payment checked: '+String(data.status).slice(0,30),o.id);return get('SELECT * FROM orders WHERE id=?',o.id); }
    const lines=all('SELECT * FROM items WHERE order_id=?',o.id); const canAllocate=!o.cancelled&&(!o.custom||o.expires>now())&&lines.every(l=>!l.variant_id||available(l.variant_id,o.id)>=l.quantity);
    if(canAllocate) for(const l of lines) if(l.variant_id) run('UPDATE variants SET stock=stock-? WHERE id=?',l.quantity,l.variant_id);
    const exception=canAllocate?'':o.cancelled?'Payment received after cancellation. Confirm refund in Paystack.':'Late payment: stock no longer available. Contact customer and confirm refund in Paystack.';
    run(`UPDATE orders SET payment='paid',reserved=0,allocated=?,fulfilment=?,exception=?,transaction_id=?,receipt=?,paid_at=? WHERE id=?`,canAllocate?1:0,canAllocate?'Paid':'On hold',exception,String(data.id),'RCT-'+o.number,now(),o.id);
    const paid=get('SELECT * FROM orders WHERE id=?',o.id);notify(paid,'Payment verified',baseUrl);audit('Payment verified; '+(canAllocate?'stock allocated':'manual resolution required'),o.id);return paid;
  }); }
  function fulfil(id,state,baseUrl) { return tx(()=>{ const o=get('SELECT * FROM orders WHERE id=?',id); if(!o) throw new Problem('Order not found',404); if(o.payment!=='paid'||!o.allocated||o.cancelled||o.refunded) throw new Problem('Order is not eligible for fulfilment'); const stages=['Paid','Preparing',o.method==='pickup'?'Ready for pickup':'Out for delivery','Completed']; if(state===o.fulfilment)return o;if(stages.indexOf(state)!==stages.indexOf(o.fulfilment)+1) throw new Problem('Choose the next fulfilment stage');run('UPDATE orders SET fulfilment=? WHERE id=?',state,id);const updated=get('SELECT * FROM orders WHERE id=?',id);notify(updated,state,baseUrl);audit('Fulfilment: '+state,id);return updated; }); }
  function cancel(id,baseUrl) {return tx(()=>{ const o=get('SELECT * FROM orders WHERE id=?',id);if(!o)throw new Problem('Order not found',404);if(o.fulfilment==='Completed')throw new Problem('Completed orders require a return/refund review'); if(o.cancelled)return o;run("UPDATE orders SET cancelled=1,reserved=0,fulfilment='Cancelled',exception=? WHERE id=?",o.payment==='paid'?'Cancellation recorded. Money is not refunded until provider confirmation.':'',id);const updated=get('SELECT * FROM orders WHERE id=?',id);notify(updated,'Order cancelled',baseUrl);audit('Cancelled; no automatic refund or restock',id);return updated;});}
  function refund(id,data,baseUrl) {return tx(()=>{const o=get('SELECT * FROM orders WHERE id=?',id);if(!o||o.payment!=='paid')throw new Problem('No paid order'); if(data.status!=='processed'||String(data.transaction?.id??data.transaction)!==o.transaction_id||data.currency!=='NGN'||!data.id)throw new Problem('Refund is not confirmed for this transaction');integer(data.amount,'refund amount',1,o.total);const prior=get('SELECT * FROM refunds WHERE id=?',String(data.id));if(prior){if(prior.order_id!==id)throw new Problem('Refund already associated with another order');return o;}if(o.refunded+data.amount>o.total)throw new Problem('Refund exceeds payment');run('INSERT INTO refunds VALUES(?,?,?,?,?)',String(data.id),id,data.amount,'processed',now());run('UPDATE orders SET refunded=refunded+? WHERE id=?',data.amount,id);const updated=get('SELECT * FROM orders WHERE id=?',id);notify(updated,'Refund confirmed '+String(data.id),baseUrl);audit('Provider-confirmed refund '+String(data.id),id);return updated;});}
  function restock(id) { return tx(()=>{const o=get('SELECT * FROM orders WHERE id=?',id);if(!o||!o.cancelled||!o.allocated||o.restocked)throw new Problem('Restock requires a cancelled, allocated order not previously restocked');for(const l of all('SELECT * FROM items WHERE order_id=?',id))if(l.variant_id)run('UPDATE variants SET stock=stock+? WHERE id=?',l.quantity,l.variant_id);run('UPDATE orders SET restocked=1 WHERE id=?',id);audit('Owner confirmed physical return and restocked',id);}); }
  function saveProduct(p) {return tx(()=>{const id=p.id||randomUUID();const old=get('SELECT * FROM products WHERE id=?',id);if(get('SELECT id FROM archived_products WHERE id=?',id))throw new Problem('This product was deleted');const photo=string(p.photo??'','photo',150,true);if(photo&&!/^\/uploads\/[a-f0-9-]+\.webp$/.test(photo)&&!(old?.photo===photo&&photo.startsWith('/sample-')))throw new Problem('Use a securely uploaded photo');const category=string(p.category,'category',30);if(!['Bags','Shoes'].includes(category))throw new Problem('Category must be Bags or Shoes');if(!Array.isArray(p.variants)||!p.variants.length||p.variants.length>60)throw new Problem('Add 1–60 variants');run('INSERT INTO products VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,category=excluded.category,photo=excluded.photo,visible=excluded.visible',id,string(p.name,'product name',120),string(p.description,'description',3000),category,photo,p.visible?1:0,old?.sample??0);
    const seen=new Set();for(const v of p.variants){const vid=v.id||randomUUID();if(seen.has(vid))throw new Problem('Duplicate variant');seen.add(vid);const existing=get('SELECT * FROM variants WHERE id=?',vid);if(existing&&existing.product_id!==id)throw new Problem('Variant belongs to another product');integer(v.stock,'quantity',0,100000);if(existing&&v.stock<existing.stock-available(vid))throw new Problem('Quantity cannot be below active reservations');run('INSERT INTO variants VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET colour=excluded.colour,size=excluded.size,price=excluded.price,cost=excluded.cost,stock=excluded.stock',vid,id,string(v.colour,'colour',80),string(v.size,'size',80),integer(v.price,'price',100,100000000),integer(v.cost,'cost',0,100000000),v.stock);}
    const omitted=all('SELECT id FROM variants WHERE product_id=?',id).filter(v=>!seen.has(v.id));if(omitted.length)throw new Problem('Keep existing variants; set stock to zero or hide the product instead');audit('Product updated: '+id);return id;}); }
  function saveSettings(s) {const clean={bagDisplay:string(s.bagDisplay??'','bag display',150,true),shoeDisplay:string(s.shoeDisplay??'','shoe display',150,true),logo:string(s.logo??'','logo',150,true),brand:string(s.brand,'brand',80),tagline:string(s.tagline,'tagline',180),ownerEmail:s.ownerEmail?email(s.ownerEmail):'',whatsapp:string(s.whatsapp??'','WhatsApp',20,true),pickupInstructions:string(s.pickupInstructions,'pickup instructions',1000),pickupTime:string(s.pickupTime,'pickup timeframe',160),lowStock:integer(s.lowStock,'low stock threshold',0,100),emailEnabled:!!s.emailEnabled,pushEnabled:!!s.pushEnabled,deliveryAreas:[]};for(const photo of [clean.bagDisplay,clean.shoeDisplay])if(photo&&!/^\/uploads\/[a-f0-9-]+\.webp$/.test(photo))throw new Problem('Use securely uploaded display photos');if(clean.logo&&clean.logo!=='/oreva-logo.jpg'&&!/^\/uploads\/[a-f0-9-]+\.webp$/.test(clean.logo))throw new Problem('Use an uploaded logo');if(clean.whatsapp&&!/^234[789]\d{9}$/.test(clean.whatsapp))throw new Problem('WhatsApp must use 234 followed by 10 digits, without +');if(!Array.isArray(s.deliveryAreas)||s.deliveryAreas.length>30)throw new Problem('Invalid delivery areas');const ids=new Set();for(const a of s.deliveryAreas){const id=string(a.id,'area id',80);if(id==='pickup'||ids.has(id))throw new Problem('Delivery IDs must be unique and cannot be pickup');ids.add(id);clean.deliveryAreas.push({id,name:string(a.name,'area name',120),fee:integer(a.fee,'fee',0,10000000),timeframe:string(a.timeframe,'delivery timeframe',160)});}run('UPDATE settings SET json=? WHERE id=1',JSON.stringify(clean));return clean;}
  function deleteProduct(id) {return tx(()=>{const p=get('SELECT * FROM products WHERE id=?',id);if(!p)throw new Problem('Product not found',404);run('UPDATE products SET visible=0 WHERE id=?',id);run('INSERT OR IGNORE INTO archived_products VALUES(?,?)',id,now());audit('Product deleted from catalogue: '+id);});}
  function publicOrder(o) { if(!o)throw new Problem('Order not found',404);const {id,number,payment,fulfilment,total,delivery,timeframe,instructions,expires,receipt,paid_at,custom,cancelled,exception,refunded,created}=o;return {id,number,payment,fulfilment,total,delivery,timeframe,instructions,expires,receipt,paid_at,custom,cancelled,exception,refunded,created,items:all('SELECT name,colour,size,quantity,price FROM items WHERE order_id=?',id)}; }
  function report() {const paid=all("SELECT * FROM orders WHERE payment='paid'");const gross=paid.reduce((a,o)=>a+o.total,0),refunds=paid.reduce((a,o)=>a+o.refunded,0),cost=paid.filter(o=>o.allocated&&!o.restocked).reduce((a,o)=>a+Number(get('SELECT COALESCE(SUM(cost*quantity),0) AS n FROM items WHERE order_id=?',o.id).n),0),expenses=Number(get('SELECT COALESCE(SUM(amount),0) AS n FROM expenses').n);return {gross,refunds,revenue:gross-refunds,cost,expenses,estimatedProfit:gross-refunds-cost-expenses,outstanding:paid.filter(o=>!o.cancelled&&o.fulfilment!=='Completed').length};}
  return {db,get,all,run,tx,settings,available,catalogue,audit,enqueue,notify,createOrder,finalize,fulfil,cancel,refund,restock,saveProduct,deleteProduct,saveSettings,publicOrder,report};
}
