import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from '../store.mjs';
import {createApp} from '../server.mjs';
import {configuration} from '../services.mjs';
test('deleted products leave catalogue and cannot be restored accidentally; order rows remain',()=>{const s=openStore(':memory:');s.saveProduct({id:'p',name:'Actual item',description:'Owner description',category:'Bags',visible:true,variants:[{id:'v',colour:'Black',size:'One',price:10000,cost:5000,stock:1}]});s.deleteProduct('p');assert.equal(s.catalogue().length,0);assert.equal(s.catalogue(true).length,0);assert.equal(s.get('SELECT stock FROM variants').stock,1);assert.throws(()=>s.saveProduct({id:'p'}),/deleted/);s.db.close();});
test('sample items are excluded from the public catalogue',()=>{const s=openStore(':memory:');s.run("INSERT INTO products VALUES('sample','Sample','Fixture','Bags','',1,1)");assert.equal(s.catalogue().length,0);s.db.close();});
test('production setup needs private code, closes after account creation, and admin still needs login',async()=>{const store=openStore(':memory:'),baseUrl='https://shop.example.test',env={OWNER_SETUP_CODE:'a'.repeat(40)},config={production:true,payment:'disabled',email:'development',baseUrl};const {server}=createApp({store,config,env});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const post=(path,data)=>fetch(url+path,{method:'POST',headers:{Origin:baseUrl,'Content-Type':'application/json'},body:JSON.stringify(data)});try{assert.equal((await fetch(url+'/api/admin/overview')).status,401);assert.equal((await post('/api/setup',{email:'owner@example.test',password:'unique-long-password',code:'wrong'})).status,403);assert.equal((await post('/api/setup',{email:'owner@example.test',password:'unique-long-password',code:env.OWNER_SETUP_CODE})).status,200);assert.equal((await fetch(url+'/api/setup').then(r=>r.json())).enabled,false);assert.equal((await post('/api/setup',{email:'other@example.test',password:'unique-long-password',code:env.OWNER_SETUP_CODE})).status,403);assert.equal((await post('/api/checkout',{})).status,503);assert.equal((await fetch(url+'/api/admin/overview')).status,401);const login=await post('/api/login',{email:'owner@example.test',password:'unique-long-password'});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/Secure/);}finally{await new Promise(r=>server.close(r));store.db.close();}});
test('unconfigured production can manage stock with checkout disabled but never simulate payment',()=>{assert.equal(configuration({NODE_ENV:'production',BASE_URL:'https://shop.example.test',PAYMENT_ADAPTER:'disabled'}).payment,'disabled');assert.throws(()=>configuration({NODE_ENV:'production',BASE_URL:'https://shop.example.test',PAYMENT_ADAPTER:'development'}));});
